# Generated by Django 4.1.1 on 2022-09-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.EmailField(default='', max_length=50)),
                ('user_nick_name', models.CharField(default='', max_length=100, verbose_name='닉네임')),
                ('user_password', models.CharField(default='', max_length=20)),
                ('user_create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'my_insta',
            },
        ),
    ]
